# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54b6286ae543774bf78025b8885bb07eb9e45630fe669f8842c68783d1cdfd47ef92b3244a0c18821f62254a1932cab15fd7fcf2594bc20cb4ca2ff4f42f3ac5

test:
  secret_key_base: 4373ddbb2808f8b15b601ae1a4b92940709d1ac56c202d7ba0c60eac4e7bef203e3ca7a4c167380e451754d71d06be245f24f04cdedfe0bea4ef6a533cba8ecf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
